# Configuration for pull request documentation previews via Netlify

[build]
    publish = "docs/build/html"
    command = "(wget https://bootstrap.pypa.io/get-pip.py -O - | python3) && python3 -m pip install tox && tox -e docs"
