# Configuration for pull request documentation previews via Netlify

[build]
    publish = "docs/build/html"
    command = "python3 -V && (wget https://bootstrap.pypa.io/get-pip.py -O - | python3) && python3 -m pip install --use-pep517 tox && tox -e docs"
