contact_links:
- name: 🤔 Have questions or need support?
  url: https://github.com/pypa/setuptools/discussions
  about: This is a place for the community to exchange ideas and recipes
- name: 💬 Discourse
  url: https://discuss.python.org/c/packaging
  about: |
    Please ask typical Q&A here: general ideas for Python packaging,
    questions about structuring projects and so on
- name: 💬 Discord (chat)
  url: https://discord.com/channels/803025117553754132/815945031150993468
  about: Chat with devs
